# NAO Project: Linear Modelling in the Pooling Framework

## Package Imports

In [2]:
!pip install ftfy

Collecting ftfy
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from ftfy) (0.2.13)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 2.8 MB/s eta 0:00:00
Installing collected packages: ftfy
Successfully installed ftfy-6.3.1

In [3]:
!pip install mord

Collecting mord
  Downloading mord-0.7.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mord
  Building wheel for mord (setup.py) ... done
  Created wheel for mord: filename=mord-0.7-py3-none-any.whl size=9885 sha256=e418cc546e0905b50f50bd1bca7618c54447fb2a5497a4d249887083444187e0
  Stored in directory: /root/.cache/pip/wheels/d1/fc/57/f2a2ad4ed0491ab6d5bb8642a90f1da9469397641e914743da
Successfully built mord
Installing collected packages: mord
Successfully installed mord-0.7

In [4]:
import kagglehub
from ftfy import fix_text
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import mord
import re
from textblob import TextBlob
import matplotlib.dates as mdates
import warnings
warnings.filterwarnings('ignore')

## Data Summary

We consider the [`skytrax-airline-reviews`](https://www.kaggle.com/datasets/efehandanisman/skytrax-airline-reviews) from Kaggle. After downloading and cleaning the data, we obtain the following cleaned data:

In [9]:
# Download latest version
path = kagglehub.dataset_download("efehandanisman/skytrax-airline-reviews")

# Define the full path to the Excel file
excel_file = os.path.join(path, "capstone_airline_reviews3.xlsx")
survey_df = pd.read_excel(excel_file)
# Dataset Duplicate Value Count
survey_df.duplicated(keep = 'first').sum()
#Dropping the Empty rows
survey_df.drop_duplicates(keep=False,inplace= True)
survey_df.reset_index(inplace=True,drop=True)
survey_df['customer_review'] = survey_df['customer_review'].apply(fix_text)
survey_df = survey_df[survey_df.isna().sum(axis=1) <= 3] # remove entries
survey_df.to_csv('capstone_airline_reviews3_cleaned.csv', index=False)
survey_df = pd.read_csv("capstone_airline_reviews3_cleaned.csv", encoding="utf-8-sig")
survey_df.head()

Downloading from https://www.kaggle.com/api/v1/datasets/download/efehandanisman/skytrax-airline-reviews?dataset_version_number=1...

100%|██████████| 23.1M/23.1M [00:00<00:00, 162MB/s]

Extracting files...

,airline,overall,author,review_date,customer_review,aircraft,traveller_type,cabin,route,date_flown,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
0,Turkish Airlines,7.0,Christopher Hackley,8th May 2019,✅ Trip Verified | London to Izmir via Istanbul...,NaN,Business,Economy Class,London to Izmir via Istanbul,2019-05-01 00:00:00,4.0,5.0,4.0,4.0,2.0,4.0,yes
1,Turkish Airlines,2.0,Adriana Pisoi,7th May 2019,✅ Trip Verified | Istanbul to Bucharest. We ma...,NaN,Family Leisure,Economy Class,Istanbul to Bucharest,2019-05-01 00:00:00,4.0,1.0,1.0,1.0,1.0,1.0,no
2,Turkish Airlines,3.0,M Galerko,7th May 2019,✅ Trip Verified | Rome to Prishtina via Istanb...,NaN,Business,Economy Class,Rome to Prishtina via Istanbul,2019-05-01 00:00:00,1.0,4.0,1.0,3.0,1.0,2.0,no
3,Turkish Airlines,10.0,Zeshan Shah,6th May 2019,✅ Trip Verified | Flew on Turkish Airlines IAD...,A330,Solo Leisure,Economy Class,Washington Dulles to Karachi,April 2019,4.0,5.0,5.0,5.0,5.0,5.0,yes
4,Turkish Airlines,1.0,Pooja Jain,6th May 2019,✅ Trip Verified | Mumbai to Dublin via Istanbu...,NaN,Solo Leisure,Economy Class,Mumbai to Dublin via Istanbul,2019-05-01 00:00:00,1.0,1.0,1.0,1.0,1.0,1.0,no

#### $X$ (explanatory) variables

**Flight Information:**
- `airline`: Which airline the flight was taken (Data type: `categorical` or `text`)
- `review_data`: The date the review was taken. (Data type: `date-time`)
- `customer_review`: The contents of the review. (Data type: `text`)
- `aircraft`: The aircraft of the flight. (Data type: `categorical` or `text`)
- `traveller_type`: The type of traveller (e.g. Business, Family Leisure, Solo Leisure). (Data type: `categorical`)
- `cabin`: The class of the undertaken flight (e.g. Economy, Business and First Class). (Data type: `categorical` or `ordinal` - can possibly be considered ordinal since Economy < Business < First Class).
- `route`: The route of the flight. (Data type: `categorical`)

**Questions with Likert-Scale Responses:**
- `data_flown`: The date of the flight taken. (Data type: `date-time`)
- `seat_comfort`: Likert-scale response to a question on seat comfort. (Data type: `ordinal`)
- `cabin_service`: Likert-scale response to a question on cabin service. (Data type: `ordinal`)
- `food_bev`: Likert-scale response to a question on food/beverage quality. (Data type: `ordinal`)
- `entertainment`: Likert-scale response to a question on entertainment. (Data type: `ordinal`)
- `ground_service`: Likert-scale response to a question on ground service. (Data type: `ordinal`)
- `value_for_money`: Likert-scale response to a question on value for money. (Data type: `ordinal`)

Note that we have ignored the `author` column, since this corresponds to a unique identifier of the row (i.e. equivalent to row ID).

#### $y$ (response) variables

- `overall`: Response to overall rating of experience of flight. (Data type: `ordinal` or possibly `continuous`)
- `recommended`: Response to whether the airline would be recommended. (Data type: `categorical`)

## Questions to Answer

We are interested in how the $y$ (response) variables are influenced by the $X$ (explanatory variables). Examples of questions we would like to answer:

- Do different questions have different $y$ effects?
- Does some question's rating influence $y$ more than another question?
- Is question rating predictive in general across all questions?
- Are some questions better at discriminating $y$ responses?
- Is the effect of a question’s rating constant across subgroups (e.g., economy vs business)?

The advantage of a **Linear Model** is that all of these questions can be framed as **hypothesis tests** on the estimated regression coefficients.

## Simplifying Assumption

#### Response Variable

For the remainder of this notebook, we only consider the `recommended` variables as our single $y$ response variable.
In general, we could:

1. **Ordinal Regression:** Consider only `overall` as the response variable within an ordinal regression model.
2. **Both Response Variables:** Consider both `recommended` and `overall` together within a [General Linear Model](https://en.wikipedia.org/wiki/General_linear_model).

In [14]:
survey_df['recommended'] = survey_df['recommended'].map({'yes': 1, 'no': 0}) # do this once


#### Explanatory Variables

In addition, we drop:
 - The `customer_review` column as an $X$ (explanatory) variable, since it would have to be dealt with separately (e.g. via a text embedding like *sentiment scores* or *transformer-based embeddings*).
 - The `route` column as an explanatory variable, since there aren't many repeated routes (running `survey_df['route'].nunique()` we obtain 24028 unique items). We could infer the length of a flight from this data and use this instead.
 - The `review_date` and `date_flown` columns - just to avoid `date-time` data.
 - The 'aircraft' column - a lot of `NaN`s present.

Let's drop all these columns (including `author`):

In [15]:
survey_df = survey_df.drop(['author', 'customer_review', 'route', 'review_date', 'date_flown', 'aircraft'], axis=1)
survey_df.head()

,airline,overall,traveller_type,cabin,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
0,Turkish Airlines,7.0,Business,Economy Class,4.0,5.0,4.0,4.0,2.0,4.0,1
1,Turkish Airlines,2.0,Family Leisure,Economy Class,4.0,1.0,1.0,1.0,1.0,1.0,0
2,Turkish Airlines,3.0,Business,Economy Class,1.0,4.0,1.0,3.0,1.0,2.0,0
3,Turkish Airlines,10.0,Solo Leisure,Economy Class,4.0,5.0,5.0,5.0,5.0,5.0,1
4,Turkish Airlines,1.0,Solo Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,0

#### Dropping all NaNs

To get a clean dataset, we drop all `NaN` values from the dataset. This avoids numerical issues in the subsequent modelling steps. Alternatively, we could impute the values.

In [16]:
survey_df = survey_df.dropna()
survey_df

,airline,overall,traveller_type,cabin,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
0,Turkish Airlines,7.0,Business,Economy Class,4.0,5.0,4.0,4.0,2.0,4.0,1
1,Turkish Airlines,2.0,Family Leisure,Economy Class,4.0,1.0,1.0,1.0,1.0,1.0,0
2,Turkish Airlines,3.0,Business,Economy Class,1.0,4.0,1.0,3.0,1.0,2.0,0
3,Turkish Airlines,10.0,Solo Leisure,Economy Class,4.0,5.0,5.0,5.0,5.0,5.0,1
4,Turkish Airlines,1.0,Solo Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...
34265,Ukraine International,1.0,Family Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,0
34266,Ukraine International,1.0,Family Leisure,Economy Class,1.0,2.0,1.0,1.0,1.0,1.0,0
34268,Ukraine International,10.0,Couple Leisure,Economy Class,5.0,5.0,5.0,4.0,4.0,4.0,1
34269,Ukraine International,2.0,Solo Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,0
34273,Ukraine International,5.0,Couple Leisure,Economy Class,1.0,1.0,1.0,3.0,1.0,5.0,0

#### Modelling Assumption

Since our response variable is the binary column `recommended`, we model it using *logistic regression*. Specifically, we assume:

$$
Y \mid X = x \sim \mathrm{Bernoulli}(\mathrm{logit}^{-1}(f(x))),
$$

where $f(x)$ is a linear model of the covariates.

## Unpooled Model

In the unpooled model, we treat each row independently and include all explanatory variables directly in the regression. We fit the following linear model for $f(x)$:

$$
f(x) = \beta^\top x,
$$

where $x$ represents a single row of the dataset, including both numerical and encoded categorical variables.

Since several explanatory variables are categorical — such as `airline`, `traveller_type`, and `cabin` — we expand them using indicator variables. The full logistic regression model becomes:

$$
\text{logit}(\Pr(Y \mid X = x)) = \beta_0
+ \sum_{i=1}^{n_a} \alpha_i \, \mathbb{1}(\text{airline} = i)
+ \sum_{i=1}^{n_t} \tau_i \, \mathbb{1}(\text{traveller\_type} = i)
+ \sum_{i=1}^{n_c} \gamma_i \, \mathbb{1}(\text{cabin} = i)
+ \sum_{j=1}^{6} \beta_j \, x_j,
$$

where the last sum runs over the six Likert-scale variables: `seat_comfort`, `cabin_service`, `food_bev`, `entertainment`, `ground_service`, and `value_for_money`.

This can be achieved using the following code:

In [17]:
import statsmodels.formula.api as smf

model = smf.logit(
    formula="""
    recommended ~ C(airline) + C(traveller_type) + C(cabin)
        + seat_comfort + cabin_service + food_bev
        + entertainment + ground_service + value_for_money
    """,
    data=survey_df
)

result = model.fit()
print(result.summary())

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.148688
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:            recommended   No. Observations:                21091
Model:                          Logit   Df Residuals:                    21004
Method:                           MLE   Df Model:                           86
Date:                Thu, 01 May 2025   Pseudo R-squ.:                  0.7853
Time:                        21:48:51   Log-Likelihood:                -3136.0
converged:                      False   LL-Null:                       -14609.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===========================================================================================================
                                              coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------
Intercept                                 -10.1538      0.558    -18.202      0.000     -11.247      -9.060
C(airline)[T.Adria Airways]                 0.8268      1.423      0.581      0.561      -1.962       3.615
C(airline)[T.Aegean Airlines]               1.1726      1.069      1.097      0.273      -0.923       3.269
C(airline)[T.Aer Lingus]                   -0.7272      0.608     -1.196      0.232      -1.919       0.465
C(airline)[T.Aeroflot Russian Airlines]    -0.4112      0.621     -0.663      0.508      -1.628       0.805
C(airline)[T.Aeromexico]                   -0.5865      0.581     -1.010      0.312      -1.724       0.551
C(airline)[T.Air Arabia]                    0.6916      1.190      0.581      0.561      -1.640       3.024
C(airline)[T.Air Canada]                   -0.1577      0.546     -0.289      0.773      -1.228       0.912
C(airline)[T.Air France]                   -0.5488      0.557     -0.985      0.325      -1.641       0.543
C(airline)[T.Air New Zealand]              -0.9229      0.595     -1.552      0.121      -2.088       0.242
C(airline)[T.AirAsia]                       0.8812      0.788      1.119      0.263      -0.662       2.425
C(airline)[T.Alaska Airlines]              -0.5509      0.649     -0.848      0.396      -1.824       0.722
C(airline)[T.Alitalia]                     -0.4446      0.641     -0.694      0.488      -1.701       0.812
C(airline)[T.American Airlines]            -0.8332      0.541     -1.540      0.124      -1.894       0.227
C(airline)[T.Asiana Airlines]              -0.3670      0.680     -0.540      0.589      -1.700       0.966
C(airline)[T.Austrian Airlines]             0.1696      0.658      0.258      0.797      -1.121       1.460
C(airline)[T.Avianca]                      -0.9017      0.660     -1.366      0.172      -2.195       0.392
C(airline)[T.Bangkok Airways]               1.2991      0.940      1.381      0.167      -0.544       3.142
C(airline)[T.British Airways]              -0.9167      0.528     -1.735      0.083      -1.952       0.119
C(airline)[T.Brussels Airlines]            -2.1250      0.767     -2.771      0.006      -3.628      -0.622
C(airline)[T.China Eastern Airlines]       -1.4090      0.599     -2.350      0.019      -2.584      -0.234
C(airline)[T.China Southern Airlines]      -0.3648      0.549     -0.664      0.506      -1.441       0.711
C(airline)[T.Copa Airlines]                 0.1052      0.754      0.140      0.889      -1.372       1.582
C(airline)[T.Delta Air Lines]              -0.5588      0.548     -1.020      0.308      -1.633       0.515
C(airline)[T.EVA Air]                      -0.2333      0.637     -0.366      0.714      -1.482       1.015
C(airline)[T.Egyptair]                     -0.4518      0.706     -0.640      0.522      -1.836       0.932
C(airline)[T.Emirates]                     -0.8798      0.532     -1.653      0.098      -1.923       0.163
C(airline)[T.Ethiopian Airlines]           -0.2479      0.607     -0.408      0.683      -1.438       0.942
C(airline)[T.Etihad Airways]               -1.0192      0.539     -1.889      0.059      -2.077       0.038
C(airline)[T.Eurowings]                    -1.0314      0.944     -1.092      0.275      -2.882       0.819
C(airline)[T.Finnair]                      -0.8616      0.590     -1.460      0.144      -2.018       0.295
C(airline)[T.Frontier Airlines]            -0.9385      0.774     -1.212      0.225      -2.456       0.579
C(airline)[T.Garuda Indonesia]              0.0617      0.617      0.100      0.920      -1.148       1.272
C(airline)[T.Germanwings]                   1.9541      2.728      0.716      0.474      -3.393       7.302
C(airline)[T.Gulf Air]                     -0.5440      0.702     -0.775      0.439      -1.921       0.833
C(airline)[T.Iberia]                       -0.4960      0.620     -0.799      0.424      -1.712       0.720
C(airline)[T.Icelandair]                   -1.1741      0.603     -1.948      0.051      -2.355       0.007
C(airline)[T.IndiGo]                       -0.6392      1.036     -0.617      0.537      -2.669       1.391
C(airline)[T.Jetblue Airways]              -1.5293      0.626     -2.444      0.015      -2.756      -0.303
C(airline)[T.KLM Royal Dutch Airlines]     -0.4493      0.561     -0.801      0.423      -1.549       0.650
C(airline)[T.Korean Air]                   -0.5146      0.649     -0.793      0.428      -1.786       0.757
C(airline)[T.Kuwait Airways]               -0.7800      0.684     -1.141      0.254      -2.120       0.560
C(airline)[T.LATAM Airlines]               -0.6753      0.615     -1.098      0.272      -1.880       0.530
C(airline)[T.LOT Polish Airlines]          -0.8451      0.671     -1.260      0.208      -2.159       0.469
C(airline)[T.Lufthansa]                    -0.3251      0.548     -0.593      0.553      -1.399       0.749
C(airline)[T.Norwegian]                    -0.3486      0.579     -0.602      0.547      -1.484       0.787
C(airline)[T.Pegasus Airlines]              0.8261      1.033      0.800      0.424      -1.199       2.851
C(airline)[T.Qantas Airways]               -0.3142      0.538     -0.584      0.559      -1.369       0.741
C(airline)[T.QantasLink]                   20.5720   6871.625      0.003      0.998   -1.34e+04    1.35e+04
C(airline)[T.Qatar Airways]                -0.6571      0.538     -1.222      0.222      -1.711       0.397
C(airline)[T.Royal Air Maroc]              -0.4352      0.743     -0.586      0.558      -1.892       1.022
C(airline)[T.Royal Jordanian Airlines]     -0.0066      0.683     -0.010      0.992      -1.346       1.333
C(airline)[T.Ryanair]                      -0.8665      0.695     -1.246      0.213      -2.229       0.496
C(airline)[T.SAS Scandinavian]             -0.8287      0.652     -1.270      0.204      -2.107       0.450
C(airline)[T.Saudi Arabian Airlines]        0.5421      0.652      0.831      0.406      -0.736       1.820
C(airline)[T.Singapore Airlines]           -0.3460      0.552     -0.627      0.530      -1.427       0.735
C(airline)[T.South African Airways]        -0.1196      0.691     -0.173      0.863      -1.474       1.234
C(airline)[T.Southwest Airlines]           -1.2428      0.625     -1.988      0.047      -2.468      -0.018
C(airline)[T.Spirit Airlines]              -0.2343      0.682     -0.344      0.731      -1.571       1.102
C(airline)[T.Sunwing Airlines]             -0.8152      0.698     -1.168      0.243      -2.183       0.552
C(airline)[T.Swiss Intl Air Lines]         -0.2460      0.578     -0.426      0.670      -1.379       0.887
C(airline)[T.TAP Portugal]                 -0.8753      0.627     -1.395      0.163      -2.105       0.354
C(airline)[T.TAROM Romanian]               -0.2882      1.203     -0.239      0.811      -2.647       2.070
C(airline)[T.Thai Airways]                 -0.3538      0.558     -0.634      0.526      -1.448       0.740
C(airline)[T.Thai Smile Airways]            0.6600      1.666      0.396      0.692      -2.605       3.925
C(airline)[T.Tunisair]                      0.8889      1.284      0.692      0.489      -1.628       3.406
C(airline)[T.Turkish Airlines]             -0.6018      0.539     -1.116      0.264      -1.658       0.455
C(airline)[T.Ukraine International]        -1.0372      0.807     -1.285      0.199      -2.619       0.544
C(airline)[T.United Airlines]              -0.8419      0.540     -1.560      0.119      -1.899       0.216
C(airline)[T.Virgin America]               -0.8973      0.854     -1.051      0.293      -2.571       0.776
C(airline)[T.Vueling Airlines]              0.5207      0.808      0.644      0.519      -1.064       2.105
C(airline)[T.WOW air]                      -0.6126      0.718     -0.854      0.393      -2.019       0.794
C(airline)[T.Wizz Air]                     -0.5408      0.859     -0.630      0.529      -2.224       1.143
C(airline)[T.easyJet]                      -0.7629      0.721     -1.059      0.290      -2.175       0.650
C(airline)[T.flydubai]                     -0.8233      0.873     -0.943      0.346      -2.534       0.888
C(traveller_type)[T.Couple Leisure]        -0.3716      0.102     -3.657      0.000      -0.571      -0.172
C(traveller_type)[T.Family Leisure]        -0.2382      0.114     -2.086      0.037      -0.462      -0.014
C(traveller_type)[T.Solo Leisure]           0.0398      0.095      0.420      0.675      -0.146       0.225
C(cabin)[T.Economy Class]                  -0.2386      0.085     -2.797      0.005      -0.406      -0.071
C(cabin)[T.First Class]                    -0.2464      0.210     -1.172      0.241      -0.658       0.165
C(cabin)[T.Premium Economy]                -0.1992      0.164     -1.216      0.224      -0.520       0.122
seat_comfort                                0.4018      0.034     11.775      0.000       0.335       0.469
cabin_service                               0.5325      0.031     17.138      0.000       0.472       0.593
food_bev                                    0.3403      0.033     10.262      0.000       0.275       0.405
entertainment                               0.1945      0.031      6.317      0.000       0.134       0.255
ground_service                              0.6780      0.028     24.331      0.000       0.623       0.733
value_for_money                             1.4019      0.039     35.885      0.000       1.325       1.479
===========================================================================================================

/usr/local/lib/python3.11/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Unfortunately, there is a numerical issue due to one of the airlines (`QantasLink` - with only four total flights) having all of their `recommended` values equalling $1$:

In [18]:
airline_outcome_counts = (
    survey_df
    .groupby('airline')['recommended']
    .value_counts()
    .unstack(fill_value=0)
)

print(airline_outcome_counts.sort_values(by=0))  # Sort by # of "no"s

recommended            0    1
airline
QantasLink             0    4
Thai Smile Airways     1   11
Germanwings            4    2
Adria Airways          4    5
Tunisair               5    5
...                  ...  ...
Emirates             491  566
Spirit Airlines      516   32
British Airways      782  475
United Airlines      987  305
American Airlines   1061  272

[75 rows x 2 columns]

To avoid, this we could either drop the whole column or remove rows who have a very small number of flights. Let's do the latter:

In [19]:
# Drop airlines with fewer than 10 rows or only one class in recommended
valid_airlines = (
    airline_outcome_counts
    [(airline_outcome_counts.sum(axis=1) >= 10) &  # enough total
     (airline_outcome_counts[0] > 0) &             # at least one "no"
     (airline_outcome_counts[1] > 0)]              # at least one "yes"
).index

survey_df = survey_df[survey_df['airline'].isin(valid_airlines)]
survey_df

,airline,overall,traveller_type,cabin,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
0,Turkish Airlines,7.0,Business,Economy Class,4.0,5.0,4.0,4.0,2.0,4.0,1
1,Turkish Airlines,2.0,Family Leisure,Economy Class,4.0,1.0,1.0,1.0,1.0,1.0,0
2,Turkish Airlines,3.0,Business,Economy Class,1.0,4.0,1.0,3.0,1.0,2.0,0
3,Turkish Airlines,10.0,Solo Leisure,Economy Class,4.0,5.0,5.0,5.0,5.0,5.0,1
4,Turkish Airlines,1.0,Solo Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...
34265,Ukraine International,1.0,Family Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,0
34266,Ukraine International,1.0,Family Leisure,Economy Class,1.0,2.0,1.0,1.0,1.0,1.0,0
34268,Ukraine International,10.0,Couple Leisure,Economy Class,5.0,5.0,5.0,4.0,4.0,4.0,1
34269,Ukraine International,2.0,Solo Leisure,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,0
34273,Ukraine International,5.0,Couple Leisure,Economy Class,1.0,1.0,1.0,3.0,1.0,5.0,0

Rerunning the model:

In [20]:
import statsmodels.formula.api as smf

model = smf.logit(
    formula="""
    recommended ~ C(airline) + C(traveller_type) + C(cabin)
        + seat_comfort + cabin_service + food_bev
        + entertainment + ground_service + value_for_money
    """,
    data=survey_df
)

result = model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.148770
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:            recommended   No. Observations:                21072
Model:                          Logit   Df Residuals:                    20988
Method:                           MLE   Df Model:                           83
Date:                Thu, 01 May 2025   Pseudo R-squ.:                  0.7852
Time:                        21:49:06   Log-Likelihood:                -3134.9
converged:                       True   LL-Null:                       -14596.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===========================================================================================================
                                              coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------
Intercept                                 -10.1501      0.558    -18.200      0.000     -11.243      -9.057
C(airline)[T.Aegean Airlines]               1.1731      1.069      1.097      0.273      -0.923       3.269
C(airline)[T.Aer Lingus]                   -0.7273      0.608     -1.196      0.232      -1.919       0.465
C(airline)[T.Aeroflot Russian Airlines]    -0.4105      0.620     -0.662      0.508      -1.627       0.806
C(airline)[T.Aeromexico]                   -0.5863      0.580     -1.010      0.312      -1.724       0.551
C(airline)[T.Air Arabia]                    0.6920      1.190      0.582      0.561      -1.639       3.023
C(airline)[T.Air Canada]                   -0.1579      0.546     -0.289      0.772      -1.227       0.912
C(airline)[T.Air France]                   -0.5488      0.557     -0.985      0.325      -1.641       0.543
C(airline)[T.Air New Zealand]              -0.9230      0.594     -1.553      0.120      -2.088       0.242
C(airline)[T.AirAsia]                       0.8807      0.787      1.119      0.263      -0.663       2.424
C(airline)[T.Alaska Airlines]              -0.5506      0.649     -0.848      0.396      -1.823       0.722
C(airline)[T.Alitalia]                     -0.4437      0.641     -0.692      0.489      -1.700       0.812
C(airline)[T.American Airlines]            -0.8330      0.541     -1.540      0.124      -1.893       0.227
C(airline)[T.Asiana Airlines]              -0.3662      0.680     -0.539      0.590      -1.699       0.966
C(airline)[T.Austrian Airlines]             0.1693      0.658      0.257      0.797      -1.120       1.459
C(airline)[T.Avianca]                      -0.9011      0.660     -1.366      0.172      -2.194       0.392
C(airline)[T.Bangkok Airways]               1.2967      0.940      1.379      0.168      -0.546       3.140
C(airline)[T.British Airways]              -0.9166      0.528     -1.736      0.083      -1.952       0.118
C(airline)[T.Brussels Airlines]            -2.1240      0.767     -2.770      0.006      -3.627      -0.621
C(airline)[T.China Eastern Airlines]       -1.4072      0.599     -2.348      0.019      -2.582      -0.233
C(airline)[T.China Southern Airlines]      -0.3640      0.549     -0.663      0.507      -1.440       0.712
C(airline)[T.Copa Airlines]                 0.1060      0.753      0.141      0.888      -1.371       1.583
C(airline)[T.Delta Air Lines]              -0.5591      0.548     -1.021      0.307      -1.633       0.515
C(airline)[T.EVA Air]                      -0.2327      0.637     -0.365      0.715      -1.481       1.016
C(airline)[T.Egyptair]                     -0.4515      0.706     -0.640      0.522      -1.835       0.932
C(airline)[T.Emirates]                     -0.8793      0.532     -1.653      0.098      -1.922       0.163
C(airline)[T.Ethiopian Airlines]           -0.2471      0.607     -0.407      0.684      -1.437       0.943
C(airline)[T.Etihad Airways]               -1.0187      0.539     -1.889      0.059      -2.076       0.038
C(airline)[T.Eurowings]                    -1.0306      0.944     -1.092      0.275      -2.881       0.819
C(airline)[T.Finnair]                      -0.8609      0.590     -1.459      0.145      -2.017       0.296
C(airline)[T.Frontier Airlines]            -0.9380      0.774     -1.212      0.226      -2.455       0.579
C(airline)[T.Garuda Indonesia]              0.0618      0.617      0.100      0.920      -1.148       1.271
C(airline)[T.Gulf Air]                     -0.5426      0.702     -0.773      0.440      -1.919       0.834
C(airline)[T.Iberia]                       -0.4956      0.620     -0.799      0.424      -1.711       0.720
C(airline)[T.Icelandair]                   -1.1736      0.603     -1.948      0.051      -2.355       0.007
C(airline)[T.IndiGo]                       -0.6394      1.035     -0.618      0.537      -2.669       1.390
C(airline)[T.Jetblue Airways]              -1.5285      0.625     -2.444      0.015      -2.754      -0.303
C(airline)[T.KLM Royal Dutch Airlines]     -0.4491      0.561     -0.801      0.423      -1.548       0.650
C(airline)[T.Korean Air]                   -0.5143      0.649     -0.793      0.428      -1.785       0.757
C(airline)[T.Kuwait Airways]               -0.7784      0.683     -1.139      0.255      -2.118       0.561
C(airline)[T.LATAM Airlines]               -0.6754      0.615     -1.099      0.272      -1.880       0.529
C(airline)[T.LOT Polish Airlines]          -0.8435      0.670     -1.258      0.208      -2.157       0.470
C(airline)[T.Lufthansa]                    -0.3251      0.548     -0.594      0.553      -1.398       0.748
C(airline)[T.Norwegian]                    -0.3480      0.579     -0.601      0.548      -1.483       0.787
C(airline)[T.Pegasus Airlines]              0.8279      1.033      0.802      0.423      -1.196       2.852
C(airline)[T.Qantas Airways]               -0.3139      0.538     -0.583      0.560      -1.369       0.741
C(airline)[T.Qatar Airways]                -0.6567      0.538     -1.222      0.222      -1.710       0.397
C(airline)[T.Royal Air Maroc]              -0.4341      0.743     -0.584      0.559      -1.891       1.022
C(airline)[T.Royal Jordanian Airlines]     -0.0058      0.683     -0.009      0.993      -1.345       1.333
C(airline)[T.Ryanair]                      -0.8654      0.695     -1.245      0.213      -2.228       0.497
C(airline)[T.SAS Scandinavian]             -0.8284      0.652     -1.270      0.204      -2.107       0.450
C(airline)[T.Saudi Arabian Airlines]        0.5436      0.652      0.834      0.404      -0.734       1.821
C(airline)[T.Singapore Airlines]           -0.3461      0.551     -0.628      0.530      -1.427       0.735
C(airline)[T.South African Airways]        -0.1197      0.691     -0.173      0.862      -1.473       1.234
C(airline)[T.Southwest Airlines]           -1.2422      0.625     -1.988      0.047      -2.467      -0.017
C(airline)[T.Spirit Airlines]              -0.2341      0.682     -0.344      0.731      -1.570       1.102
C(airline)[T.Sunwing Airlines]             -0.8148      0.697     -1.168      0.243      -2.182       0.552
C(airline)[T.Swiss Intl Air Lines]         -0.2456      0.578     -0.425      0.671      -1.379       0.887
C(airline)[T.TAP Portugal]                 -0.8747      0.627     -1.395      0.163      -2.104       0.355
C(airline)[T.TAROM Romanian]               -0.2867      1.203     -0.238      0.812      -2.645       2.071
C(airline)[T.Thai Airways]                 -0.3530      0.558     -0.633      0.527      -1.447       0.740
C(airline)[T.Thai Smile Airways]            0.6594      1.664      0.396      0.692      -2.603       3.922
C(airline)[T.Tunisair]                      0.8892      1.284      0.692      0.489      -1.628       3.406
C(airline)[T.Turkish Airlines]             -0.6013      0.539     -1.116      0.265      -1.657       0.455
C(airline)[T.Ukraine International]        -1.0356      0.807     -1.284      0.199      -2.617       0.545
C(airline)[T.United Airlines]              -0.8417      0.539     -1.560      0.119      -1.899       0.216
C(airline)[T.Virgin America]               -0.8967      0.854     -1.050      0.294      -2.570       0.776
C(airline)[T.Vueling Airlines]              0.5202      0.808      0.644      0.520      -1.064       2.104
C(airline)[T.WOW air]                      -0.6121      0.717     -0.853      0.393      -2.018       0.794
C(airline)[T.Wizz Air]                     -0.5392      0.859     -0.628      0.530      -2.222       1.144
C(airline)[T.easyJet]                      -0.7610      0.720     -1.056      0.291      -2.173       0.651
C(airline)[T.flydubai]                     -0.8224      0.873     -0.942      0.346      -2.533       0.888
C(traveller_type)[T.Couple Leisure]        -0.3732      0.102     -3.673      0.000      -0.572      -0.174
C(traveller_type)[T.Family Leisure]        -0.2406      0.114     -2.107      0.035      -0.464      -0.017
C(traveller_type)[T.Solo Leisure]           0.0367      0.095      0.387      0.699      -0.149       0.222
C(cabin)[T.Economy Class]                  -0.2379      0.085     -2.789      0.005      -0.405      -0.071
C(cabin)[T.First Class]                    -0.2457      0.210     -1.169      0.242      -0.658       0.166
C(cabin)[T.Premium Economy]                -0.1989      0.164     -1.214      0.225      -0.520       0.122
seat_comfort                                0.4019      0.034     11.777      0.000       0.335       0.469
cabin_service                               0.5334      0.031     17.156      0.000       0.472       0.594
food_bev                                    0.3396      0.033     10.240      0.000       0.275       0.405
entertainment                               0.1949      0.031      6.328      0.000       0.135       0.255
ground_service                              0.6780      0.028     24.332      0.000       0.623       0.733
value_for_money                             1.4005      0.039     35.846      0.000       1.324       1.477
===========================================================================================================

### Evaluating Unpooled Approach: Likert-Scale Variables Only

Due to the large number of different airlines, let's just drop everything apart from the Likert Scale questions. So, our model is:

$$
\text{logit}(\Pr(Y \mid X = x)) = \beta_0  + \sum_{j=1}^{6} \beta_j \, x_j.
$$

In [21]:
cleaned_df = survey_df.drop(['airline', 'traveller_type', 'cabin'], axis=1)
cleaned_df

,overall,seat_comfort,cabin_service,food_bev,entertainment,ground_service,value_for_money,recommended
0,7.0,4.0,5.0,4.0,4.0,2.0,4.0,1
1,2.0,4.0,1.0,1.0,1.0,1.0,1.0,0
2,3.0,1.0,4.0,1.0,3.0,1.0,2.0,0
3,10.0,4.0,5.0,5.0,5.0,5.0,5.0,1
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0
...,...,...,...,...,...,...,...,...
34265,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0
34266,1.0,1.0,2.0,1.0,1.0,1.0,1.0,0
34268,10.0,5.0,5.0,5.0,4.0,4.0,4.0,1
34269,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0
34273,5.0,1.0,1.0,1.0,3.0,1.0,5.0,0

In [22]:
import statsmodels.formula.api as smf

model = smf.logit(
    formula="""
    recommended ~  seat_comfort + cabin_service + food_bev
        + entertainment + ground_service + value_for_money
    """,
    data=cleaned_df
)

result = model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.152815
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:            recommended   No. Observations:                21072
Model:                          Logit   Df Residuals:                    21065
Method:                           MLE   Df Model:                            6
Date:                Thu, 01 May 2025   Pseudo R-squ.:                  0.7794
Time:                        21:49:21   Log-Likelihood:                -3220.1
converged:                       True   LL-Null:                       -14596.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         -11.0829      0.183    -60.676      0.000     -11.441     -10.725
seat_comfort        0.4162      0.033     12.692      0.000       0.352       0.480
cabin_service       0.5480      0.030     18.417      0.000       0.490       0.606
food_bev            0.3598      0.032     11.230      0.000       0.297       0.423
entertainment       0.1634      0.028      5.822      0.000       0.108       0.218
ground_service      0.6841      0.027     25.696      0.000       0.632       0.736
value_for_money     1.3832      0.037     37.239      0.000       1.310       1.456
===================================================================================

#### Interpretation

All six Likert-scale predictors are statistically significant (p < 0.001). Their coefficients represent the log-odds change of recommending the airline per 1-point increase in rating:

| Predictor         | Coef | Interpretation (holding others constant)                                                |
|-------------------|------|-------------------------------------------------------------------------------------------|
| **Intercept**     | –11.30 | Base log-odds when all ratings are zero (all the other rating increases must overcome the -11.30 value) |
| **Seat Comfort**  | +0.438 | Each unit increase in seat comfort increases log-odds of recommending by 0.438 (~55% increase in odds) |
| **Cabin Service** | +0.551 | Very strong effect — increases odds by ~73% per unit                                  |
| **Food & Bev**    | +0.398 | Moderate effect — increases odds by ~49% per unit                                     |
| **Entertainment** | +0.177 | Small but significant effect (~19% increase per unit)                                 |
| **Ground Service**| +0.676 | Strong effect — increases odds by ~97% per unit                                       |
| **Value for Money**| **+1.389** | **Largest effect** — each unit increase multiplies odds by ~4 (exp(1.389))              |

#### Limitation of Unpooled Modelling

The unpooled (“wide-format”) approach suffers from several limitations, especially when it comes to hypothesis testing and scalability to a higher number of question-answer variables. For example:

1. **No natural framework for comparing slopes**  
   - We need to fit separate coefficients for each question-rating variable (e.g. `seat_comfort`, `food_bev`, etc.), then manually construct and test contrasts (e.g. “Is the effect of `seat_comfort` significantly larger than that of `food_bev`?”).  
   - In contrast, a *pooled model* can evaluate these comparisons directly via $H_0: \beta_{\text{food\_bev}} - \beta_{\text{seat\_comfort}} = 0$.

2. **Inflexible handling of missing data**  
   - Any row with a missing rating for *any* question must be dropped (or imputed separately for each variable), leading to variable sample sizes per coefficient.  
   - The *pooled framework* allows you to drop (or model) missingness at the question-response level, preserving more data.

3. **Scalability of number of parameters**  
   - As the number of question-answer variables grows, the number of predictors in the unpooled model grows linearly (one coefficient per question). Testing interactions with other covariates (e.g. question × traveller_type) becomes combinatorially large.  
   - The pooled model keeps a compact design: one factor for `Question_ID` plus one rating variable (with interaction), regardless of how many questions you add.

4. **Lack of partial pooling/shrinkage**  
   - Unpooled estimates are “no pooling” — each coefficient stands alone, even if some questions have few responses. This can lead to high variance and overfitting.  
   - A multilevel or even a fixed-effect pooled model borrows strength across questions, reducing bias and variance in estimates for sparse categories (questions with a few responses).

5. **Hard to infer group-level effects**  
   - To ask “Do cabin-service ratings matter more for Business travellers than Family travellers?” you’d need to add and test a three-way interaction for each question separately.  
   - In the pooled framework, you simply include `C(Question_ID) * Rating * C(traveller_type)` and perform joint tests on the interaction terms.

## Pooling Framework

To perform pooling, we introduce a `Question_ID` and `rating` $X$ (explanatory variable). This is sometimes called rewriting the data-frame in "long-format".

In [24]:
likert_cols = [
    'seat_comfort',
    'cabin_service',
    'food_bev',
    'entertainment',
    'ground_service',
    'value_for_money'
]

cleaned_df_long = pd.melt(
    survey_df,
    id_vars=['recommended','overall'],    # keep recommended with each row
    value_vars=likert_cols,     # turn these columns into rows
    var_name='Question_ID',        # name for the former-column labels
    value_name='rating'         # name for the former-cell values
)

cleaned_df_long

        recommended  overall      Question_ID  rating
0                 1      7.0     seat_comfort     4.0
1                 0      2.0     seat_comfort     4.0
2                 0      3.0     seat_comfort     1.0
3                 1     10.0     seat_comfort     4.0
4                 0      1.0     seat_comfort     1.0
...             ...      ...              ...     ...
126427            0      1.0  value_for_money     1.0
126428            0      1.0  value_for_money     1.0
126429            1     10.0  value_for_money     4.0
126430            0      2.0  value_for_money     1.0
126431            0      5.0  value_for_money     5.0

[126432 rows x 4 columns]

Since our outcome remains the binary `recommended`, in the pooled (long-format) framework we model each question–response pair $(Q, R)$ as

$$ Y \mid Q = q,\;R = r
\;\sim\;\mathrm{Bernoulli}\!\bigl(\mathrm{logit}^{-1}\bigl(f(q,r)\bigr)\bigr), $$

where the linear predictor is

$$ f(q, r)
= \beta_{0} + \beta_1 \, r
+ \sum_{j=1}^{6}\alpha_{j}\,\mathbf{1}(Q=j)
+ \sum_{j=1}^{6}\delta_{j}\,\mathbf{1}(Q=j)\,r. $$

Equivalently:

$$
\begin{align*}
\text{logit}\bigl(\Pr(Y=1\mid Q,R)\bigr)
&= \beta_{0} + \beta_{1} \,R
+ \sum_{j=1}^{6}\alpha_{j}\,\mathbf{1}(Q=j)
+ \sum_{j=1}^{6}\delta_{j}\,\mathbf{1}(Q=j)\,R \\
&= \underbrace{\beta_{0} + \sum_{j=1}^{6}\alpha_{j}\,\mathbf{1}(Q=j)}_{\text{question‐specific intercepts}}
\;+\;
\underbrace{\beta_{1}\,R}_{\text{global slope}}
\;+\;
\underbrace{\sum_{j=1}^{6}\delta_{j}\,\mathbf{1}(Q=j)\,R}_{\text{question‐specific deviations in slope}}.
\end{align*}
$$

Here:

- $\alpha_{j}$ captures the question-specific intercept shift for question $j$.  
- $\delta_{j}$ allows the slope of the rating $R_i$ to vary by question.  

This single model lets us directly compare both baseline effects $\alpha_j$ and rating effects $\delta_j$ across all questions.

This can be implemented using the following code:

In [25]:
model = smf.logit(
    formula="""
    recommended ~  C(Question_ID) + C(Question_ID) * rating
    """,
    data=cleaned_df_long
)

result = model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.349947
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:            recommended   No. Observations:               126432
Model:                          Logit   Df Residuals:                   126420
Method:                           MLE   Df Model:                           11
Date:                Thu, 01 May 2025   Pseudo R-squ.:                  0.4948
Time:                        21:49:58   Log-Likelihood:                -44245.
converged:                       True   LL-Null:                       -87574.
Covariance Type:            nonrobust   LLR p-value:                     0.000
============================================================================================================
                                               coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
Intercept                                   -5.6147      0.077    -72.820      0.000      -5.766      -5.464
C(Question_ID)[T.entertainment]              2.1101      0.091     23.212      0.000       1.932       2.288
C(Question_ID)[T.food_bev]                   1.1084      0.097     11.405      0.000       0.918       1.299
C(Question_ID)[T.ground_service]             1.0945      0.097     11.235      0.000       0.904       1.285
C(Question_ID)[T.seat_comfort]               0.3848      0.105      3.663      0.000       0.179       0.591
C(Question_ID)[T.value_for_money]           -1.7207      0.133    -12.956      0.000      -1.981      -1.460
rating                                       1.6006      0.020     79.342      0.000       1.561       1.640
C(Question_ID)[T.entertainment]:rating      -0.4355      0.025    -17.415      0.000      -0.484      -0.386
C(Question_ID)[T.food_bev]:rating           -0.0730      0.028     -2.650      0.008      -0.127      -0.019
C(Question_ID)[T.ground_service]:rating     -0.1043      0.027     -3.854      0.000      -0.157      -0.051
C(Question_ID)[T.seat_comfort]:rating        0.0516      0.029      1.768      0.077      -0.006       0.109
C(Question_ID)[T.value_for_money]:rating     0.7357      0.038     19.228      0.000       0.661       0.811
============================================================================================================

#### Interpretation

##### 1. Baseline (Reference)—**Cabin Service**  
- **Intercept** = –5.5916:
  This is the log-odds of “recommended = 1” when `Question_ID = cabin_service` and `rating = 0`.  (Rating = 0 is outside the 1–5 scale, so this intercept is just the mathematical anchor.)  
- **rating** = +1.6039:
  For **cabin_service**, each one-point increase in rating multiplies the odds of recommending by $\exp(1.6039)\approx4.97$.  

##### 2. Question-specific intercept shifts  
Each of these tells you how the baseline log-odds (at rating = 0) for that question differs from `cabin_service`’s intercept:

| Question             | Coef        | Interpretation                                                       |
|----------------------|-------------|------------------------------------------------------------------------|
| entertainment        | +2.0481     | At rating=0, entertainment starts ~7.8× higher odds than cabin_service ($\exp(2.0481)\approx7.75$).  |
| food_bev             | +1.0546     | food_bev starts ~2.87× higher odds.                                    |
| ground_service       | +1.0751     | ground_service starts ~2.93× higher odds.                              |
| seat_comfort         | +0.3097     | seat_comfort starts ~1.36× higher odds.                                |
| value_for_money      | –1.8162     | value_for_money starts ~0.16× the odds (much lower baseline).          |


##### 3. Question-specific deviations in slope  
These interaction terms show how each question’s *rating slope* differs from the **baseline slope** of 1.6039:

| Question             | Interaction | Slope (total)                   | Odds-ratio per unit rating                |
|----------------------|-------------|----------------------------------|-------------------------------------------|
| cabin_service        | —           | **1.6039**                       | $\exp(1.6039)\approx4.97$               |
| entertainment        | –0.4166     | 1.6039 – 0.4166 = **1.1873**      | $\exp(1.1873)\approx3.28$               |
| food_bev             | –0.0538     | 1.6039 – 0.0538 = **1.5501**      | $\exp(1.5501)\approx4.71$               |
| ground_service       | –0.1154     | 1.6039 – 0.1154 = **1.4885**      | $\exp(1.4885)\approx4.43$               |
| seat_comfort         | +0.0651     | 1.6039 + 0.0651 = **1.6690**      | $\exp(1.6690)\approx5.31$               |
| value_for_money      | +0.7460     | 1.6039 + 0.7460 = **2.3499**      | $\exp(2.3499)\approx10.48$              |

To summarise:

1. **All coefficients are highly significant** (p < 0.05), so none of these effects are due to chance.  
2. **Value for Money** has by far the steepest slope: a one-point increase multiplies the odds of recommending by over $10\times$, compared to $\approx 5\times$ for the average question.  
3. **Seat Comfort** and **food & beverage** also have slopes above the baseline, indicating they’re slightly more predictive than cabin service.  
4. **Entertainment** has the weakest rating effect ($\approx3.3\times$ odds per point), despite its high intercept shift—meaning people start out more likely to recommend after answering the entertainment question, but additional points matter less.  

Altogether, the output confirms that **not all questions are equally predictive**: some dimensions (especially value for money) drive recommendation far more strongly than others.

### Comparison of Pooled vs. Unpooled

- The unpooled model tells you how important each question is on its own, but leaves you to do all inter-question comparisons by hand.

- The pooled model gives you both a global sense of how ratings drive recommendation and—via the interaction terms—exactly how and by how much each question deviates from that global effect, all within one coherent hypothesis-testing framework.

For example, here is a concrete hypothesis you can answer directly from the pooled model output—but cannot without extra work in the unpooled (“wide”) model:

> **Question:** Is the effect of “value_for_money” ratings on the odds of recommending the airline significantly larger than the average rating effect across all questions?

#####  Pooled model

From the summary, we obtained:

- `rating`: with coefficient $\beta_1 = 1.6039$. This is the "global" slope - the *average* effect across questions.
- `C(Question_ID)[T.value_for_money]:rating`: with coefficeint $\delta_{\text{vfm}} = 0.7460$. This is the question-specific *slope deviation* for `value_for_money`.

To answer the question above, we perform the hypothesis:

$$ H_0:\;\delta_{\text{vfm}} = 0
\quad\Longleftrightarrow\quad
\underbrace{\beta_1 + \delta_{\text{vfm}}}_{\text{slope for vfm}}
\;=\;
\underbrace{\beta_1}_{\text{average slope}} $$

The obtained p-value for `C(Question_ID)[T.value_for_money]:rating` directly tests whether the `value_for_money` slope differs from the *average* slope.  Here, $\delta_{\text{vfm}}=0.7460$ with $p<0.001$, so we conclude:

> **The rating effect of value_for_money is significantly larger than the average rating effect across all questions.**

#### Why the unpooled model can’t answer that directly

In the unpooled (“wide”) model we obtained get six separate slopes $\hat\beta_{\text{seat}},\dots,\hat\beta_{\text{vfm}}$.  But there is **no “global” slope** in the model to compare against.  To test

\[
\hat\beta_{\text{vfm}}
\;>\;\frac{1}{6}\bigl(\hat\beta_{\text{seat}} + \cdots + \hat\beta_{\text{vfm}}\bigr),
\]

you’d have to:

1. **Compute** the six estimated coefficients,
2. **Average** them,
3. **Manually compute** the variance of that average (using the joint covariance matrix of the six estimates),
4. **Form** a \(t\)- or Wald–statistic,
5. **Look up** its p-value.

That process is **tedious, error-prone**, and not directly supported by a single line of output.  

---

### 3. Take-away

- **Pooled model** gives you a **global slope** and **per-question deviations** with **direct p-values** for “deviation = 0” (i.e.\ “does this question’s slope differ from the global average?”).  
- **Unpooled model** lacks a global parameter, so comparing any individual coefficient to the overall mean requires manual contrasts.

This is why **pooling** unlocks hypothesis tests about **“how each question’s effect relates to the overall effect”** in a single, coherent framework.

In [31]:
import statsmodels.api as sm
from statsmodels.miscmodels.ordinal_model import OrderedModel

# 1. Prepare the formula and data
formula = 'overall ~  C(Question_ID) + C(Question_ID) * rating'

# 2. Create and fit the ordinal model (logit link)
model_ordinal = OrderedModel.from_formula(
    formula,
    data=cleaned_df_long,
    distr='logit'  # Use 'probit' for ordered probit
)
result_ordinal = model_ordinal.fit(method='bfgs')  # Optimization method

# 3. Print results
print(result_ordinal.summary())

Optimization terminated successfully.
         Current function value: 1.665710
         Iterations: 78
         Function evaluations: 81
         Gradient evaluations: 81
                             OrderedModel Results
==============================================================================
Dep. Variable:                overall   Log-Likelihood:            -2.1060e+05
Model:                   OrderedModel   AIC:                         4.212e+05
Method:            Maximum Likelihood   BIC:                         4.214e+05
Date:                Thu, 01 May 2025
Time:                        21:59:02
No. Observations:              126432
Df Residuals:                  126412
Df Model:                          11
============================================================================================================
                                               coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
C(Question_ID)[T.entertainment]              0.7742      0.044     17.464      0.000       0.687       0.861
C(Question_ID)[T.food_bev]                   0.5218      0.044     11.892      0.000       0.436       0.608
C(Question_ID)[T.ground_service]             0.5119      0.044     11.750      0.000       0.426       0.597
C(Question_ID)[T.seat_comfort]              -0.0065      0.047     -0.139      0.889      -0.098       0.085
C(Question_ID)[T.value_for_money]           -0.0537      0.045     -1.201      0.230      -0.141       0.034
rating                                       1.4618      0.010    152.967      0.000       1.443       1.480
C(Question_ID)[T.entertainment]:rating      -0.0758      0.012     -6.079      0.000      -0.100      -0.051
C(Question_ID)[T.food_bev]:rating            0.0334      0.012      2.709      0.007       0.009       0.058
C(Question_ID)[T.ground_service]:rating      0.0014      0.012      0.112      0.911      -0.022       0.025
C(Question_ID)[T.seat_comfort]:rating        0.1206      0.013      9.362      0.000       0.095       0.146
C(Question_ID)[T.value_for_money]:rating     0.1354      0.012     11.058      0.000       0.111       0.159
1.0/2.0                                      2.6145      0.034     77.666      0.000       2.549       2.680
2.0/3.0                                     -0.1851      0.008    -21.855      0.000      -0.202      -0.168
3.0/4.0                                     -0.4855      0.010    -48.097      0.000      -0.505      -0.466
4.0/5.0                                     -0.9103      0.013    -70.722      0.000      -0.935      -0.885
5.0/6.0                                     -0.8825      0.013    -68.700      0.000      -0.908      -0.857
6.0/7.0                                     -0.9496      0.013    -71.210      0.000      -0.976      -0.924
7.0/8.0                                     -0.4505      0.010    -44.669      0.000      -0.470      -0.431
8.0/9.0                                     -0.0195      0.008     -2.501      0.012      -0.035      -0.004
9.0/10.0                                     0.2502      0.007     35.550      0.000       0.236       0.264
============================================================================================================

### Interpretation of the Ordered Logistic Regression Results

#### **Model Overview**
- **Dependent Variable**: `overall` (ordinal rating, likely 1–10).
- **Method**: Maximum Likelihood Estimation (converged successfully).
- **Observations**: 126,432 reviews.
- **Key Metrics**:
  - **Log-Likelihood**: -210,600 (baseline for model comparison).
  - **AIC/BIC**: 421,200/421,400 (used for model selection).

### **Key Findings**
#### **1. Main Effects (Question Categories)**
- **Entertainment**: Significant positive effect (`coef=0.7742, p<0.001`).  
  - Passengers who rated "entertainment" higher had 2.17x higher odds (`exp(0.7742)`) of a better overall rating.  
- **Food & Beverage**: Positive effect (`coef=0.5218, p<0.001`).  
- **Ground Service**: Positive effect (`coef=0.5119, p<0.001`).  
- **Seat Comfort** and **Value for Money**: Not significant (p=0.889 and p=0.230).

#### **2. Interaction Effects (Question × Rating)**
- **Entertainment × Rating**: Negative interaction (`coef=-0.0758, p<0.001`).  
  - The positive effect of entertainment diminishes as the rating increases.  
- **Seat Comfort × Rating**: Strong positive interaction (`coef=0.1206, p<0.001`).  
  - Seat comfort becomes more influential at higher ratings.  
- **Value for Money × Rating**: Positive interaction (`coef=0.1354, p<0.001`).  
  - Value for money gains importance as ratings increase.

#### **3. Rating Variable**
- **Main Effect**: Strong positive coefficient (`coef=1.4618, p<0.001`).  
  - A 1-unit increase in the predictor variable `rating` (likely an aggregated score) leads to a 1.46-unit increase in the log-odds of a higher overall rating.  

#### **4. Cutpoints (Thresholds Between Ratings)**
- **1.0/2.0**: Large threshold (`coef=2.6145`), indicating a steep jump from the lowest rating (1) to the next (2).  
- **9.0/10.0**: Positive threshold (`coef=0.2502`), suggesting higher ratings are more easily distinguished.  
- **Mid-range thresholds (e.g., 7.0/8.0)**: Negative coefficients, reflecting natural clustering of mid-tier ratings.


### **Business Implications**
1. **Entertainment and Food Drive Satisfaction**:  
   - Focus on improving in-flight entertainment and meal quality for immediate impact.  
2. **Seat Comfort Matters at High Ratings**:  
   - Luxury/priority services should emphasize seat comfort to retain high-tier customers.  
3. **Value for Money Gains Importance**:  
   - Budget airlines should highlight cost-effectiveness to boost overall ratings.  


### **Actionable Recommendations**
- **Target Entertainment and Food Quality**:  
  - Partner with content providers for better in-flight entertainment.  
  - Upgrade meal options for premium cabins.  
- **Optimize Seat Comfort for High-Rating Customers**:  
  - Offer seat upgrades or premium seating options.  
- **Leverage Value for Money**:  
  - Promote competitive pricing and loyalty rewards for budget-conscious travelers.